language: generic
sudo: required
services:
- docker
script:
- make verify build test images
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: munnerz/keepalived-cloud-provider
    branch: master